### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marki123** [Dasrg/steam-group-member-boost#1]
[eathadderc4nguyen3947] Unable to auth (Error: Error: CAPTCHA
    at SteamCommunity.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\steamcommunity\index.js:155:13)
    at Request._callback (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12) {
  captchaurl: 'https://steamcommunity.com/login/rendercaptcha/?gid=3763278844859601168'
})
[edkingcrabi723pucci] Unable to auth (Error: Error: CAPTCHA
    at SteamCommunity.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\steamcommunity\index.js:155:13)
    at Request._callback (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\steamcommunity\components\http.js:67:15)
    at Request.self.callback (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\request\request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (C:\Users\markg\Desktop\cmdb\steam-group-member-boost-master\steam-group-member-boost-master\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12) {
  captchaurl: 'https://steamcommunity.com/login/rendercaptcha/?gid=3763278844859601185'
})

**Comment by hoshic** [comment]
Same issue here
